[package]
name = "raytraceweekend"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"
indicatif = "0.18"
rand = "0.9.2"

[dev-dependencies]
rstest = "0.26"
test-log = { version = "0.2", features = ["trace"] }
