[package]
name = "raytraceweekend"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
env_logger = "0.11"

[dev-dependencies]
rstest = "0.26.1"
test-log = { version = "0.2", features = ["trace"] }
